=== Todo:

* *DONE* Create key pair for the admin node to use in the deployment
** *CONCERN* Biggest problem is getting the public key for the student host, to populate each cluster nodes' authorized_keys file 
** Instructor host needs to have the public keys of all student hosts
*** The authorized keys file for each deployment will contain:
**** Instructor host
**** Student host
**** Admin node

* *DONE* Copy .all_nodes and ssh_config files to the admin node

* *DONE* Remove load balancer

* Test deploying onto multiple KVM hosts
** Run ssh-agent and ensure you have passwordless ssh and sudo on the target host
----
terraform apply -state=state/infra1.tfstate -var libvirt_uri="qemu+ssh://admin@infra1.susecon.local/system"
terraform apply -state=state/infra2.tfstate -var libvirt_uri="qemu+ssh://admin@infra2.susecon.local/system"
terraform apply -state=state/infra3.tfstate -var libvirt_uri="qemu+ssh://admin@infra3.susecon.local/system"
terraform apply -state=state/infra4.tfstate -var libvirt_uri="qemu+ssh://admin@infra4.susecon.local/system"
----


*  Love to be able to do nested deployments

* Deploy a single deployment across multiple KVM hosts (providers)
** https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-instances

* Need to work out a way to snapshot all environments after they've been deployed
** Also need a programatic way to rollback one or all environments


==== NFS storage class
* From: https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#helm_tiller_install

----
you only need to run the following command from the location where you normally run skuba commands:

sudo zypper install helm

This will install Tiller without additional certificate security.

kubectl create serviceaccount --namespace kube-system tiller

kubectl create clusterrolebinding tiller \
    --clusterrole=cluster-admin \
    --serviceaccount=kube-system:tiller

helm init \
    --tiller-image registry.suse.com/caasp/v4/helm-tiller:2.16.1 \
    --service-account tiller

----



// vim: set syntax=asciidoc:

